# main.py
#S%%writefile main.py
import os

def print_instructions():
    print("--- Facial Emotion, Gender, Age & Animated Emote Mirroring App (for Google Colab) ---")
    print("\nThis project demonstrates a multi-task learning model with real-time animated emote mirroring in Colab.")
    print("\n--- Setup Instructions in Google Colab ---")
    print("1. **Create a new Colab Notebook** (File -> New notebook).")
    print("2. **Set Runtime Type to GPU** (Runtime -> Change runtime type -> Hardware accelerator: GPU).")
    print("\n3. **Google Drive Setup (Verify Existing Folders & Upload Animated Emotes):**")
    print("   a. Ensure your project files (`.py` files, `haarcascade_frontalface_default.xml`) are already present in:")
    print("      `/content/drive/MyDrive/Face Emotion Recogization`")
    print("   b. Ensure your UNZIPPED DATASET is in a 'data' subfolder, located at:")
    print("      `/content/drive/MyDrive/Face Emotion Recogization/data`")
    print("      (This 'data' folder should contain 'emotion_data', 'gender_data', 'age_data' subfolders).")
    print("   c. **NEW: Create an 'assets' folder with an 'emotes' subfolder.** Inside 'emotes', create 7 subfolders (one for each emotion: 'angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise').")
    print("      Upload your transparent PNG animation frames (e.g., `happy_01.png`, `happy_02.png`) into their respective emotion subfolders:")
    print("      `/content/drive/MyDrive/Face Emotion Recogization/assets/emotes/happy/happy_01.png` etc.")
    print("   d. In a Colab cell, **mount your Google Drive and verify paths**:")
    print("      ```python")
    print("      import os")
    print("      import sys")
    print("      from google.colab import drive")
    print("      ")
    print("      drive.mount('/content/drive')")
    print("      MAIN_PROJECT_PATH = '/content/drive/MyDrive/Face Emotion Recogization'")
    print("      DATASET_ROOT_PATH = os.path.join(MAIN_PROJECT_PATH, 'data')")
    print("      EMOTE_ASSET_PATH = os.path.join(MAIN_PROJECT_PATH, 'assets', 'emotes')")
    print("      if MAIN_PROJECT_PATH not in sys.path:")
    print("          sys.path.append(MAIN_PROJECT_PATH)")
    print("      ")
    print("      print(f'\\nMain project files expected in: {MAIN_PROJECT_PATH}')")
    print("      print(f'Dataset expected in: {DATASET_ROOT_PATH}')")
    print("      print(f'Emote assets expected in: {EMOTE_ASSET_PATH}')")
    print("      !ls -l '{MAIN_PROJECT_PATH}' # Verify project files")
    print("      !ls -l '{DATASET_ROOT_PATH}' # Verify dataset folders")
    print("      !ls -l '{EMOTE_ASSET_PATH}' # Verify emote subfolders")
    print("      !ls -l '{EMOTE_ASSET_PATH}/happy' # Verify example emote frames")
    print("      # Crucial: Check the output of `ls -l` commands for exact paths and contents.")
    print("      ```")

    print("\n4. **Create Project Files in Colab's Session Storage:**")
    print("   Copy and paste the content of `utils.py`, `model.py`, `predict.py`, AND **emotemirroring.py** into separate Colab code cells.")
    print("   Use the `%%writefile filename.py` magic command at the very top of each cell to save the content to a file (e.g., `%%writefile utils.py`). Run each cell.")

    print("\n5. **Install Dependencies (in a new Colab cell):**")
    print("   ```python")
    print("   !pip install tensorflow opencv-python numpy matplotlib scikit-learn")
    print("   ```")

    print("\n--- How to Run (Execute these in separate Colab cells) ---")
    print("1. **Train the model:**")
    print("   ```python")
    print("   import os")
    print("   MAIN_PROJECT_PATH_COLAB = '/content/drive/MyDrive/Face Emotion Recogization'")
    print("   ACTUAL_DATASET_PATH = os.path.join(MAIN_PROJECT_PATH_COLAB, 'data')")
    print("   ")
    print("   print('Starting model training...')")
    print("   %run '{MAIN_PROJECT_PATH_COLAB}/model.py'")
    print("   ```")
    print("   This will train the model and save `final_multi_task_vgg16_model.h5` in your project's main Google Drive directory.")

    print("\n2. **Run real-time prediction (with Animated Emote Mirroring):**")
    print("   ```python")
    print("   import os")
    print("   MAIN_PROJECT_PATH_COLAB = '/content/drive/MyDrive/Face Emotion Recogization'")
    print("   ")
    print("   print('Starting real-time prediction...')")
    print("   %run '{MAIN_PROJECT_PATH_COLAB}/predict.py'")
    print("   ```")
    print("   This will open your webcam in the Colab output and display predictions with an overlaid animated emote.")
    print("   **Important**: Grant webcam permissions when prompted. To stop the webcam stream, click the **square 'Stop' button** in the Colab cell's output or interrupt the runtime (Runtime -> Interrupt execution).")

if __name__ == '__main__':
    print_instructions()